enable warnings as errors more selectively
-warnings-as-errors=* causes problems on rvc-release special targets:
  {cf_x86_phone,taimen}_analyzer-userdebug

Turns off:
  /buildbot/src/googleplex-android/rvc-release/system/netd/server/BandwidthController.cpp:817:13: error: use !absl::StartsWith instead of find() != 0 [abseil-string-find-startswith,-warnings-as-errors]
        if (rule.find(NEW_CHAIN_COMMAND) != 0) continue;
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            !absl::StartsWith(rule, NEW_CHAIN_COMMAND)
  /buildbot/src/googleplex-android/rvc-release/system/netd/server/BandwidthController.cpp:821:13: error: use !absl::StartsWith instead of find() != 0 [abseil-string-find-startswith,-warnings-as-errors]
        if (chainName.find("bw_costly_") != 0 || chainName == std::string("bw_costly_shared")) {
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            !absl::StartsWith(chainName, "bw_costly_")

Test: builds
Bug: 153035880
Signed-off-by: Maciej Żenczykowski <maze@google.com>
Change-Id: Iede66c4016b450100abb82590fba6f1dfcd3bb2f